import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/home.module.css'
import Bottom from '../components/Bottom'
import Footer from '../components/Footer'
import Nav from '../components/Nav'

export default function About() {
    
    return (
        <div className={styles.container}>
            <Head>
                <title>About Us | Assure Business & Communication</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/Assure-Biz-icon.png" />
            </Head>
            
            <main className={styles.main}>
                <Nav />
                
                <div className='banners'>
                    <h1>About Us</h1>
                </div>
                
                <div className="dual_section">
                    <div className='container'>
                        <section className='text'>
                            <h2>Who we are</h2>
                            <p>We are a conveyancing team who works together with pride to bring out the best of our abilities in die world of IT & Technology. We care for our customers and help wherever we can. We believe with hard work comes great achievements.</p>
                        </section>
                        <section>
                            <Image src={"/working.jpg"} alt="" width="700" height={466.9} />
                        </section>
                    </div>
                </div>
                
                <div className={`dual_section white_bac`}>
                    <div className='container'>
                        <section className='text'>
                            <h2>How We Became Assure Technologies</h2>
                            <p>Thyme IT  was growing at a fast pace, with adding 8 new additional employees came a huge change in the company, we have different divisions in Assure Technology that did not make all that much sense to Thyme IT.</p>
                            <p>We have not only grown as a IT Company but have grown along with Assure Studios our partnered company. We evaluated what would be the best outcome for Thyme IT, and that was to merge all our services into one company called Assure Industries which Assure Techcnologies & Assure Studios fall under. </p>
                            <p>We are proud of how far we come and with the rapid rate that we are expanding we look forward to what our future in Assure industries and at Assure technologies looks like.</p>
                        </section>
                        <section>
                            <Image src={"/techly.jpg"} alt="" width="500" height={700} />
                        </section>
                    </div>
                </div>
                
                <div className="quad_section">
                    <div className='container'>
                        <section>
                            <h2>What Makes Us Different?</h2>
                            <p>We don’t work on a Break-Fix scheme, resulting in downtime. We take responsibility for every IT service, providing an end-to-end solution before systems become unstable.</p>
                        </section>
                        <section>
                            <h2>Services We Specialise In</h2>
                            <p>Microsoft-based solutions, thus allowing you to maintain your initial competitive advantage without the increased risk associated with large businesses that rely on technology solutions. We provide dynamic services and specialized support for midmarket businesses as well as strategic consulting services for enterprise businesses.</p>
                        </section>
                        <section>
                            <h2>Why Choose Us?</h2>
                            <p>We strive to provide our customers with a highly professional IT service in a timely manner that exceeds our customers’ expectations, offering a variety of services to optimize your technology environment for you.</p>
                        </section>
                        <section>
                            <h2>SLA</h2>
                            <p>Providing SLAs (Service Level Agreements) at affordable monthly rates ensures that our customers get the service they need.</p>
                        </section>
                    </div>
                </div>
                
                <Bottom />
                
                
            </main>
            
            <Footer />
        </div>
    )
}
