import Head from 'next/head'
import styles from '../styles/home.module.css'
import { useTheme, Button } from '@nextui-org/react'
import Hero from '../components/Hero'
import Footer from '../components/Footer'
import Nav from '../components/Nav'
import Bottom from '../components/Bottom'
import Link from 'next/link'

export default function Home() {
    const { theme } = useTheme();
    
    return (
        <div className={styles.container}>
            <Head>
                <title>Home | Assure Business & Communication</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/Assure-Biz-icon.png" />
            </Head>
            
            <main className={styles.main}>
                <Nav />
                
                {/* <Components /> */}
                
                {/* <Bottom /> */}
                
                <Hero />
                
                <div className={`${styles.section}`}>
                    <div className={`container ${styles.flex}`}>
                        <section className={`${styles.num_part} ${styles.flex}`}>
                            <h1>01</h1>
                            <h5>ABOUT US</h5>
                        </section>
                        <section className={styles.det_part}>
                            <div className={`${styles.det_part_body} ${styles.about}`}>
                                <p>We are a conveyancing team who works together with pride to bring out the best of our abilities in die world of IT & Technology. We care for our customers and help wherever we can. We believe with hard work comes great achievements.</p>
                                
                                <Link href='/about'>About Us</Link>
                            </div>
                            <div className={`${styles.det_part_footer}  ${styles.flex}  ${styles.justify}`}>
                                <h1>COMPUTER NETWORKING</h1>
                                <h1>SYSTEM MAINTENANCE</h1>
                                <h1>IT SOLUTIONS & CONSULTANCY</h1>
                            </div>
                        </section>
                    </div>
                </div>
                
                <div className={`${styles.section}`}>
                    <div className={`container ${styles.flex}`}>
                        <section className={`${styles.num_part} ${styles.flex}`}>
                            <h1>02</h1>
                            <h5>SERVICES</h5>
                        </section>
                        <section className={`${styles.det_part} ${styles.services_gradient}`}>
                            <div className={styles.det_part_body}>
                                <h1>We pride ourselves in proactive IT solutions & comprehensive support.</h1>
                                <p>We just happen to provide excellent IT Service.</p>
                                
                                <Link href='/services'>Services</Link>
                            </div>
                        </section>
                    </div>
                </div>
                
                <div className={`${styles.section}`}>
                    <div className={`container ${styles.flex}`}>
                        <section className={`${styles.num_part} ${styles.flex}`}>
                            <h1>03</h1>
                            <h5>LEVERAGING TECHNOLOGY</h5>
                        </section>
                        <section className={`${styles.det_part} ${styles.leverage}`}>
                            <div className={styles.det_part_body}>
                                <h1>Leveraging Technology</h1>
                                <Link href='/leveragingtech'>Leveraging Technology</Link>
                            </div>
                        </section>
                    </div>
                </div>
                
                <div className={`${styles.section}`}>
                    <div className={`container ${styles.flex}`}>
                        <section className={`${styles.num_part} ${styles.flex}`}>
                            <h1>04</h1>
                            <h5>OUR SLA</h5>
                        </section>
                        <section className={`${styles.det_part} ${styles.sla}`}>
                            <div className={styles.det_part_body}>
                                <h1>Our SLA Responsibilities</h1>
                                <ul>
                                    <li>Communication and Negotiation with all 3rd Party ICT providers while prioritizing The Client’s specific needs.</li>
                                    <li>Provide realistic expectations of provider.</li>
                                    <li>Providing Priority Support whenever required outside of scheduled monthly visits.</li>
                                    <li>Access to a permanent Helpdesk, providing ongoing and continued Remote.</li>
                                </ul>
                                <Link href='/sla'>OUR SLA</Link>
                            </div>
                        </section>
                    </div>
                </div>
                
                <Bottom />
                
            </main>
            
            <Footer />
        </div>
    )
}
